name: zkp-analysis
version: 0.1

library:
  source-dirs: 
    - src
    - src/CP_Analysis
    - src/Value_Inferencer
  exposed-modules:
    - ValueAnalysis.Analysis
    - ValueDomain.Domain
    - CPAnalysis.Analysis
    - CPDomain.Domain
    - Syntax.AST
    - Syntax.Compiler
    - ValueAnalysis.UserRules
    - ValueAnalysis.VariableState
    - ValueAnalysis.ValueDomain
    - ValueAnalysis.Printer
    - BugDetection.BugDetection
  other-modules:
    - Paths_zkp_analysis
  dependencies:
    - base > 4.7 && < 5
    - rio
    - maf2-syntax
    - maf2-domains
    - maf2-analysis
    - mtl
    - singletons
    - containers

executables:
  zkp-analysis-exe:
    source-dirs: app
    main: Main.hs
    dependencies:
      - zkp-analysis
      - rio
      - base > 4.7 && < 5
      - maf2-analysis
      - maf2-domains
      - maf2-syntax
      - containers
    other-modules:
      - Paths_zkp_analysis

tests:
  all-tests:
    main: TestRunner.hs
    source-dirs: test
    dependencies:
      - base > 4.7 && < 5
      - rio
      - maf2-analysis
      - maf2-domains
      - maf2-syntax
      - zkp-analysis
      - containers
      - hspec
    other-modules:
      - Syntax.ExpressionsParseTest
      - Syntax.IteParseTest
      - CP_Analysis.Analysis.FullyConstrainedTest
      - CP_Analysis.Analysis.ExpressionsAnalysisTest
      - Value_Inferencer.ValueAnalysis.Num2BitsTest
      - Value_Inferencer.ValueAnalysis.NonZeroTest
      - Value_Inferencer.ValueAnalysis.NonZeroTemplateTest
      - Value_Inferencer.ValueAnalysis.LessThanTest
      - Value_Inferencer.BugDetection.SortTest
      - Value_Inferencer.BugDetection.Veridise.Edwards2MontgomeryWrongTest
      - Value_Inferencer.BugDetection.Veridise.Edwards2MontgomeryFixedTest
      - Value_Inferencer.BugDetection.Veridise.Montgomery2EdwardsWrongTest
      - Value_Inferencer.BugDetection.Veridise.Montgomery2EdwardsFixedTest
      - Value_Inferencer.BugDetection.Veridise.MontgomeryAddWrongTest
      - Value_Inferencer.BugDetection.Veridise.MontgomeryAddFixedTest
      - Value_Inferencer.BugDetection.Veridise.MontgomeryDoubleWrongTest
      - Value_Inferencer.BugDetection.Veridise.MontgomeryDoubleFixedTest
      - Value_Inferencer.BugDetection.TrailOfBits.ToBinaryTest
      - Value_Inferencer.BugDetection.TrailOfBits.EnforceAuthTest
      - Value_Inferencer.BugDetection.Arrays.ArrayTagTest
      - Value_Inferencer.BugDetection.Arrays.ArraySelectOutOfBoundsTest
      - Value_Inferencer.BugDetection.Arrays.ArrayStoreOutOfBoundsTest
      - Value_Inferencer.BugDetection.TaggedCircomlib.DecoderTestRaw
      - Value_Inferencer.BugDetection.TaggedCircomlib.DecoderTestBinary
      - Value_Inferencer.BugDetection.TaggedCircomlib.DecoderTestNoOutputTag
      - Value_Inferencer.BugDetection.TaggedCircomlib.BinSubTest
      - Value_Inferencer.BugDetection.TaggedCircomlib.BinSubTestDeep
