name: ccc-check
version: 1.0.0
synopsis: Language-agnostic detection of computation-constraint inconsistencies in ZKP programs
license: MIT
category: Cryptography, Security, Static Analysis

library:
  source-dirs:
    - src
    - src/ValueInference
  exposed-modules:
    - ValueAnalysis.Analysis
    - ValueDomain.Domain
    - Syntax.AST
    - Syntax.Compiler
    - ValueAnalysis.UserRules
    - ValueAnalysis.VariableState
    - ValueAnalysis.ValueDomain
    - ValueAnalysis.Printer
    - BugDetection.BugDetection
  other-modules:
    - Paths_ccc_check
  dependencies:
    - base > 4.7 && < 5
    - rio
    - maf2-syntax
    - maf2-domains
    - maf2-analysis
    - mtl
    - singletons
    - containers
    - deepseq

executables:
  ccc-check:
    source-dirs: app
    main: Main.hs
    dependencies:
      - ccc-check
      - rio
      - base > 4.7 && < 5
      - maf2-analysis
      - maf2-domains
      - maf2-syntax
      - containers
    other-modules:
      - Paths_ccc_check

tests:
  all-tests:
    main: TestRunner.hs
    source-dirs: test
    dependencies:
      - base > 4.7 && < 5
      - rio
      - maf2-analysis
      - maf2-domains
      - maf2-syntax
      - ccc-check
      - containers
      - hspec
    other-modules:
      - Syntax.ExpressionsParseTest
      - Syntax.IteParseTest
      - ValueInference.ValueAnalysis.Num2BitsTest
      - ValueInference.ValueAnalysis.NonZeroTest
      - ValueInference.ValueAnalysis.NonZeroTemplateTest
      - ValueInference.ValueAnalysis.LessThanTest
      - ValueInference.BugDetection.SortTest
      - ValueInference.BugDetection.Veridise.Edwards2MontgomeryWrongTest
      - ValueInference.BugDetection.Veridise.Edwards2MontgomeryFixedTest
      - ValueInference.BugDetection.Veridise.Montgomery2EdwardsWrongTest
      - ValueInference.BugDetection.Veridise.Montgomery2EdwardsFixedTest
      - ValueInference.BugDetection.Veridise.MontgomeryAddWrongTest
      - ValueInference.BugDetection.Veridise.MontgomeryAddFixedTest
      - ValueInference.BugDetection.Veridise.MontgomeryDoubleWrongTest
      - ValueInference.BugDetection.Veridise.MontgomeryDoubleFixedTest
      - ValueInference.BugDetection.TrailOfBits.ToBinaryTest
      - ValueInference.BugDetection.TrailOfBits.EnforceAuthTest
      - ValueInference.BugDetection.Arrays.ArrayTagTest
      - ValueInference.BugDetection.Arrays.ArraySelectOutOfBoundsTest
      - ValueInference.BugDetection.Arrays.ArrayStoreOutOfBoundsTest
      - ValueInference.BugDetection.TaggedCircomlib.DecoderTestRaw
      - ValueInference.BugDetection.TaggedCircomlib.DecoderTestBinary
      - ValueInference.BugDetection.TaggedCircomlib.DecoderTestNoOutputTag
      - ValueInference.BugDetection.TaggedCircomlib.ModSumTest

      - ValueInference.BugDetection.TaggedCircomlib.NotTest
      - ValueInference.BugDetection.TaggedCircomlib.XorTest
      - ValueInference.BugDetection.TaggedCircomlib.AndTest
      - ValueInference.BugDetection.TaggedCircomlib.OrTest
      - ValueInference.BugDetection.TaggedCircomlib.NandTest
      - ValueInference.BugDetection.TaggedCircomlib.NorTest
      - ValueInference.BugDetection.TaggedCircomlib.IsZeroTest
      - ValueInference.BugDetection.TaggedCircomlib.IsZeroForcedTest
      - ValueInference.BugDetection.TaggedCircomlib.IsEqualTest
      - ValueInference.BugDetection.TaggedCircomlib.IsEqualForcedTest
      - ValueInference.BugDetection.TaggedCircomlib.Num2BitsTest
      - ValueInference.BugDetection.TaggedCircomlib.Bits2NumTest
      - ValueInference.BugDetection.TaggedCircomlib.MultiMux1Test
      - ValueInference.BugDetection.TaggedCircomlib.Mux1Test
      - ValueInference.BugDetection.TaggedCircomlib.LessThanTest
      - ValueInference.BugDetection.TaggedCircomlib.GreaterThanTest
      - ValueInference.BugDetection.TaggedCircomlib.GreaterEqThanTest
      - ValueInference.BugDetection.TaggedCircomlib.LessEqThanTest
      - ValueInference.BugDetection.TaggedCircomlib.BigLessThanTest
      - ValueInference.BugDetection.TaggedCircomlib.BinSubTest
      - ValueInference.BugDetection.TaggedCircomlib.BinSubTestDeep
      - ValueInference.BugDetection.TaggedCircomlib.BinSumTest
      - ValueInference.BugDetection.TaggedCircomlib.SumTestDeep

benchmarks:
      
  taggedcircomlib-bench:
    main: TaggedCircomlibBench.hs
    source-dirs:
      - evaluation/benchmarks
      - test
    other-modules:
      - ValueInference.BugDetection.TaggedCircomlib.NotTest
      - ValueInference.BugDetection.TaggedCircomlib.XorTest
      - ValueInference.BugDetection.TaggedCircomlib.AndTest
      - ValueInference.BugDetection.TaggedCircomlib.OrTest
      - ValueInference.BugDetection.TaggedCircomlib.NandTest
      - ValueInference.BugDetection.TaggedCircomlib.NorTest
      - ValueInference.BugDetection.TaggedCircomlib.IsZeroTest
      - ValueInference.BugDetection.TaggedCircomlib.DecoderTestRaw
      - ValueInference.BugDetection.TaggedCircomlib.IsEqualTest
      - ValueInference.BugDetection.TaggedCircomlib.Num2BitsTest
      - ValueInference.BugDetection.TaggedCircomlib.Bits2NumTest
      - ValueInference.BugDetection.TaggedCircomlib.MultiMux1Test
      - ValueInference.BugDetection.TaggedCircomlib.Mux1Test
      - ValueInference.BugDetection.TaggedCircomlib.LessThanTest
      - ValueInference.BugDetection.TaggedCircomlib.GreaterThanTest
      - ValueInference.BugDetection.TaggedCircomlib.GreaterEqThanTest
      - ValueInference.BugDetection.TaggedCircomlib.LessEqThanTest
      - ValueInference.BugDetection.TaggedCircomlib.BigLessThanTest
      - ValueInference.BugDetection.TaggedCircomlib.BinSubTest
      - ValueInference.BugDetection.TaggedCircomlib.BinSumTest
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - base
      - ccc-check
      - criterion
      - deepseq
      - containers
      - rio
      - maf2-analysis
      - maf2-domains
      - maf2-syntax
      - hspec
