name: zkp-analysis
version: 0.1

library:
  source-dirs: 
    - src
    - src/CP_Analysis
    - src/Value_Inferencer
  exposed-modules:
    - ValueAnalysis.Analysis
    - ValueDomain.Domain
    - CPAnalysis.Analysis
    - CPDomain.Domain
    - Syntax.AST
    - Syntax.Compiler
    - ValueAnalysis.UserRules
    - ValueAnalysis.VariableState
    - ValueAnalysis.ValueDomain
    - ValueAnalysis.Printer
  other-modules:
    - Paths_zkp_analysis
  dependencies:
    - base > 4.7 && < 5
    - rio
    - maf2-syntax
    - maf2-domains
    - maf2-analysis
    - mtl
    - singletons
    - containers

executables:
  zkp-analysis-exe:
    source-dirs: app
    main: Main.hs
    dependencies:
      - zkp-analysis
      - rio
      - base > 4.7 && < 5
      - maf2-analysis
      - maf2-domains
      - maf2-syntax
      - containers
    other-modules:
      - Paths_zkp_analysis

tests:
  all-tests:
    main: TestRunner.hs
    source-dirs: test
    dependencies:
      - base > 4.7 && < 5
      - rio
      - maf2-analysis
      - maf2-domains
      - maf2-syntax
      - zkp-analysis
      - containers
      - hspec
    other-modules:
      - Syntax.ExpressionsParseTest
      - CP_Analysis.Analysis.FullyConstrainedTest
      - Syntax.IteParseTest
      - CP_Analysis.Analysis.ExpressionsAnalysisTest
      - Value_Inferencer.Analysis.Num2BitsTest
      - Value_Inferencer.Analysis.NonZeroTest
      - Value_Inferencer.Analysis.NonZeroTemplateTest
      - Value_Inferencer.Analysis.LessThanTest
      - Bug_Detector.SortTest
      - Value_Inferencer.Analysis.Edwards2MontgomeryWrongTest
      - Value_Inferencer.Analysis.Edwards2MontgomeryFixedTest
